name: core
description: A new Flutter package project.
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  app_links: ^3.4.2
  flutter_easyloading: 3.0.5
  package_info: ^2.0.2
  logger: ^1.3.0
  intl: ^0.17.0
  url_launcher: ^6.1.10
  flutter_bloc: ^8.1.2
  dartz: 0.10.1
  shared_dependencies:
    path: ../shared_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.3

flutter:
